### ISSUE TITLE
Hotkey and Menu Entry not available

### ISSUE THREAD

**Issue by tbvogel** [controlflow/resharper-gotoword#7]
I have installed the plugin v0.9.7 with Resharper 8.0.2000.2660 and VS 2012 v11.0.61030.00 Update 4 and restarted Visual Studio. But the functionalities are not accessible via Hotkey (Triple Ctrl+T) or displayed as Menu Item in Resharper > Navigate > Go To Word. The Command "Resharper_GotoWordIndex" under Tools > Option > Environment > Keyboard is not existing.

**Comment by controlflow** [comment]
Closing as obsolete. You should be able to assign any hotkey for "GoToText" action in R# 2016.2 without problem.
